#!/usr/bin/env python3
"""Generate remotion/src/FullVideo/timeline.ts from scene-map.json + graphics-data.json.

Re-run after any scene-map/graphics-data change. Plate tier is resolved here:
plates-hq/<span>.mov (neural) wins over plates/<span>.mov (fast) when present.
"""
import json
from pathlib import Path

JOB = Path(__file__).resolve().parents[1]
R = JOB / "graphics-build/remotion"
FPS = 25

m = json.load(open(JOB / "graphics-build/scene-map.json"))
try:
    gd = json.load(open(JOB / "graphics-build/graphics-data.json"))
except FileNotFoundError:
    gd = {}
    print("WARN: graphics-data.json missing — spans get placeholder graphics")

DISCLAIMER_F = 3 * FPS          # 75
BASE_OFFSET = DISCLAIMER_F      # base-cut t0 lands at delivery frame 75

spans = []
for s in m["spans"]:
    f0 = round(s["t0"] * FPS)
    f1 = round(s["t1"] * FPS)
    # plates are PNG sequences served over localhost (graphics-build/plates/, NOT bundled):
    # plates-seq-hq/<span>/ (neural) beats plates-seq/<span>/ (fast)
    P = JOB / "graphics-build/plates"
    hq = (P / "plates-seq-hq" / s["id"] / "f00000.png").exists()
    fast = (P / "plates-seq" / s["id"] / "f00000.png").exists()
    plate = (f"http://127.0.0.1:8877/plates-seq-hq/{s['id']}" if hq
             else (f"http://127.0.0.1:8877/plates-seq/{s['id']}" if fast else None))
    spans.append({
        "id": s["id"], "type": s["frameType"],
        "from": BASE_OFFSET + f0, "durationInFrames": max(1, f1 - f0),
        "baseF0": f0,
        "plate": plate if s["frameType"] in (1, 2, 3) else None,
        "plateTier": "hq" if hq else ("fast" if fast else "none"),
        "transition": (s.get("transitionIn") or {}).get("kind", "hard cut"),
        "script": s.get("scriptText", ""),
        "graphics": gd.get(s["id"]),
        "notes": s.get("notes", ""),
    })

base_len = round(m["spans"][-1]["t1"] * FPS)
fixed = {
    "fps": FPS,
    "disclaimerFrames": DISCLAIMER_F,
    "baseOffset": BASE_OFFSET,
    "baseLenFrames": base_len,
    # brand transition overlays the timeline at the p04 marker (base 55.083s), 2.03s
    "brandTransition": {"from": BASE_OFFSET + round(55.083 * FPS), "durationInFrames": round(2.03 * FPS)},
    "subscribe": [
        {"from": BASE_OFFSET + round(47.43 * FPS), "durationInFrames": round(5.0 * FPS)},
        {"from": BASE_OFFSET + round(807.33 * FPS), "durationInFrames": round(5.0 * FPS)},
    ],
    "endscreen": {"from": BASE_OFFSET + base_len, "durationInFrames": 10 * FPS},
    "legalStatic": {"from": BASE_OFFSET + base_len + 10 * FPS, "durationInFrames": 10 * FPS},
    "crawl": {"from": BASE_OFFSET + base_len + 20 * FPS, "durationInFrames": round(5.5 * FPS)},
}
fixed["totalFrames"] = fixed["crawl"]["from"] + fixed["crawl"]["durationInFrames"]

out = R / "src/FullVideo/timeline.ts"
out.parent.mkdir(parents=True, exist_ok=True)
tiers = {"hq": 0, "fast": 0, "none": 0}
for s in spans:
    if s["type"] in (1, 2, 3): tiers[s["plateTier"]] += 1
out.write_text(
    "// GENERATED by graphics-build/gen_timeline.py — do not edit by hand\n"
    f"export const FIXED = {json.dumps(fixed, indent=1)} as const;\n"
    f"export const SPANS = {json.dumps(spans, ensure_ascii=False, indent=1)};\n"
)
print(f"timeline.ts: {len(spans)} spans, total {fixed['totalFrames']} frames "
      f"({fixed['totalFrames']/FPS:.1f}s), plates: {tiers}")
